# **TITANIC SURVIVOR ANALYSIS**

In [27]:
import pandas as pd
import numpy as np

READING DATA USING PANDAS

We use pandas read_csv function to read  csv file in python and pandas DataFrame method to convert file into the data frame.

In [28]:
df = pd.DataFrame(pd.read_csv('/content/train.csv'))
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [29]:
df.shape

(891, 12)

In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
 # df.isnull().sum() returns a panda series with column names as the label index
 # and totsl count of null values in the column as its value 
 # And we are storing only those colunms which have more than 35% of the data missing.

x = df.isnull().sum()
drop_col = x[x>(35/100 * df.shape[0])]
drop_col

Cabin    687
dtype: int64

In [32]:
drop_col.index

Index(['Cabin'], dtype='object')

In [ ]:
df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

In [ ]:
df.fillna(df.mean(), inplace = True)
df.isnull().sum()

In [41]:
df['Embarked'].describe()

count     891
unique      3
top         S
freq      646
Name: Embarked, dtype: object

In [39]:
df['Embarked'].fillna('S',inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df.corr()

In [44]:
df['FamilySize']=df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis=1, inplace=True)
df.corr()

             PassengerId  Survived    Pclass       Age      Fare  FamilySize
PassengerId     1.000000 -0.005007 -0.035144  0.033207  0.012658   -0.040143
Survived       -0.005007  1.000000 -0.338481 -0.069809  0.257307    0.016639
Pclass         -0.035144 -0.338481  1.000000 -0.331339 -0.549500    0.065997
Age             0.033207 -0.069809 -0.331339  1.000000  0.091566   -0.248512
Fare            0.012658  0.257307 -0.549500  0.091566  1.000000    0.217138
FamilySize     -0.040143  0.016639  0.065997 -0.248512  0.217138    1.000000

In [45]:
df['Alone']= [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

   PassengerId  Survived  Pclass  ... Embarked FamilySize  Alone
0            1         0       3  ...        S          1      0
1            2         1       1  ...        C          1      0
2            3         1       3  ...        S          0      1
3            4         1       1  ...        S          1      0
4            5         0       3  ...        S          0      1

[5 rows x 11 columns]

In [47]:
df.groupby(['Alone'])['Survived'].mean()

Alone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

In [49]:
df[['Alone','Fare']].corr()

          Alone      Fare
Alone  1.000000 -0.271832
Fare  -0.271832  1.000000

In [51]:
df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

Sex
0    0.188908
1    0.742038
Name: Survived, dtype: float64

In [52]:
df.groupby(['Embarked'])['Survived'].mean()

Embarked
C    0.553571
Q    0.389610
S    0.339009
Name: Survived, dtype: float64

CONCLUSION



* Female passenges were prioritized over men.
*People with high class or rich people have higher survival rate than others.The hierarichy might have been followed while saving passengers.
*Passengers travelling with their family have higher survival rate.
*Passengers who boarded ship at Cherbourg,survived more in proportion then the others.